### ISSUE TITLE
for Creating a new recipient. even for 202 responses, I got an Exception

### ISSUE THREAD

**Issue by pedramham** [rapidmail/rapidmail-apiv3-client-php#14] opened 2023-03-23 13:46 UTC
Hello . for [Creating](https://github.com/rapidmail/rapidmail-apiv3-client-php/blob/master/docs/recipients-services.md#create-a-new-recipient) a new recipient. Even if the item is added to the list and I get 202 response , I get it with an Exception. can you check it, please? thank you
![Screenshot from 2023-03-23 17-41-47](https://user-images.githubusercontent.com/21017276/227222224-08a9e9a2-4478-45ec-a275-1d37dd414d7f.png)

**Comment by eth8505** [comment] 2023-03-23 14:21
@pedramham which PHP version and operating system are you using? This may be a duplicate of issue #6 ?

**Comment by pedramham** [comment] 2023-03-23 15:32
@eth8505 I use PHP 8.1 . OP is Ubuntu 22.04.2 LTS
```

PHP 8.1.2-1ubuntu2.11 (cli) (built: Feb 22 2023 22:56:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.11, Copyright (c), by Zend Technologies
```

**Comment by eth8505** [comment] 2023-03-23 15:51
@pedramham can you try updating to current 8.1 version 8.1.17 please?

**Comment by pedramham** [comment] 2023-03-24 08:17
@eth8505 Yes that's right. i tried with Php 8.2. Thank you

**Comment by eth8505** [comment] 2023-03-24 08:23
Great. I added a section about problematic PHP-Versions to the README.md.

**Closed as completed by eth8505** 2023-03-24 08:23 UTC
Labels: duplicate

**Comment by pedramham** [comment] 2023-03-24 09:34
@eth8505 sorry shame on me :-) .  it doesn't work still. problem is here. can you check it, please?
I hope this issue helps you.
https://github.com/openssl/openssl/issues/18866

```
Rapidmail\ApiClient\Http\HttpClientFacade;

    /**
     * @inheritDoc
     */
    public function request($method, $uri, array $options = [])
    {
        dd($this->client->request($method, $uri, $options));
        try {
            return $this->client->request($method, $uri, $options);
        } catch (GuzzleException $e) {
            throw ApiException::fromGuzzleException($e);
        }

    }
```
                                                                                                                                                                                                
 ```
 [GuzzleHttp\Exception\RequestException (201)]                                                                                                                                                 
  cURL error 56: OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apiv3.emailsys.net/  
  v1/recipients      
```

![Screenshot from 2023-03-24 13-33-18](https://user-images.githubusercontent.com/21017276/227481756-9ff1ea1e-17e5-4aa0-bcee-e45f7ebf54d6.png)

value is 

```
array:2 [
  "json" => array:11 [
    "email" => "michael2@example.com"
    "recipientlist_id" => 438
    "firstname" => "Michael J."
    "gender" => "male"
    "title" => "Prof. Dr."
    "zip" => "7687"
    "birthdate" => "1974-01-23"
    "foreign_id" => "121"
    "mailtype" => "text"
    "extra1" => "Extra 1"
    "status" => "active"
  ]
  "query" => []
]
```

**Comment by eth8505** [comment] 2023-03-24 10:01
@pedramham SSL isn't handled by the apiclient or even the underlying guzzle library, but rather by your system as well as php and openssl installed on your system. I recommend updating packages on your ubuntu and retrying if it works.

**Comment by pedramham** [comment] 2023-03-24 19:51
I have the latest version of OpenSSL.  I follow this [issue](https://github.com/openssl/openssl/issues/18866) and installed nginx/1.22.1 but didn't help.
[link](https://whmcs.community/topic/320212-openssl-curl-error-56-openssl-ssl_read-error0a000126ssl-routinesunexpected-eof-while-reading-errno-0-issue-on-non-cpanel-whmcs/)

```
 php -i | grep -i openssl
SSL Version => OpenSSL/3.0.2
libSSH Version => libssh/0.9.6/openssl/zlib
openssl
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 3.0.2 15 Mar 2022
OpenSSL Header Version => OpenSSL 3.0.2 15 Mar 2022
Openssl default config => /usr/lib/ssl/openssl.cnf
openssl.cafile => no value => no value
openssl.capath => no value => no value
Native OpenSSL support => enabled
```

**Comment by eth8505** [comment] 2023-03-27 08:59
@pedramham usually SSL-Issues come from some issue with the host operating system itself, I've never actually seen any issues caused by PHP itself. You could try updating your ca-certificates package. If that doesn't help, maybe you can try testing the connection manually? This might give hints to what the actual issue is. 
Try this command
```
openssl s_client -connect apiv3.emailsys.net:443 -servername apiv3.emailsys.net
```

**Comment by pedramham** [comment] 2023-03-28 06:45
Thank you @eth8505 after running that command I got this. any idea? 

---
```
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: AE577B65669EC975F9253DEB2A1E7172C50747F4607479E61E49ABE1C1067CD2
    Session-ID-ctx: 
    Resumption PSK: 2D26A7ACC1A00B834834E9485998D395BB6082ABE7BBADFCD6464435B33F00540288BEC79702C5CB33EDE87621D3A743
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 1800 (seconds)
    TLS session ticket:
    0000 - e1 94 ca 00 84 7b 2a b5-81 5d 85 ca 27 6c ee 66   .....{*..]..'l.f
    0010 - e1 8d 75 09 47 fd bf 32-55 71 5f 26 b9 b3 44 03   ..u.G..2Uq_&..D.

    Start Time: 1679984888
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
read
HTTP/1.1 400 Bad Request
Server: nginx
Date: Tue, 28 Mar 2023 06:28:14 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 150
Connection: close

<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
40D7D13AF87F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:../ssl/record/rec_layer_s3.c:308:

```

**Comment by eth8505** [comment] 2023-03-28 07:43
@pedramham that's indeed very weird. You're using Ubuntu 22.04 LTS and sury.org PHP-Packages I'm guessing? 22.04 with sury.org PHP packages is what I'm using, but I'm not having such issues.
But since you're having the issue when opening raw SSL-connections and not just when running our API client with PHP this is definitely nothing to do with our API client. Frankly, I'm also out of ideas how to fix this. If I could have reproduce the issue, I might have been able to figure something out, but under these circumstances, sadly, I'm at a loss. 
If you figure out what's going on, please let me know.
